### ISSUE TITLE
ValueError: Expected the value in a schema to be a string, but got: <class 'swagger_to.swagger.RawDict'>

### ISSUE THREAD

**Issue by stevenxuwoss** [Parquery/swagger-to#132]
if definitions properties has name with description, will cause this issue
```
  DeviceDefineInfoRes:
    type: object
    discriminator: ''
    properties:
      createPerson:
        type: string
      createTime:
        type: string
      description:
        type: string
      id:
        type: string
      manufacturer:
        type: string
      name:
        type: string
      number:
        type: string
      productTypeCode:
        type: integer
        format: int32
      updatePerson:
        type: string
      updateTime:
        type: string
    description: ''
```
<img width="729" alt="20211027104911" src="https://user-images.githubusercontent.com/17000812/138991549-b512b07d-f789-4df9-8436-92e87c698d4c.png">

*(@mristin, 2021-10-27: added markers for multi-line code)*
